### PR TITLE
Upgrade and align Python OS images

### PR DESCRIPTION
**Pull request by S0obi**
Hello there,

I am opening a PR to fix a trivial misalignment in the project Dockerfile.
You didn't mention anything about contributions in your documentation, feel free to decline the PR if it's not useful.

Please note that I selected main as a target branch for this PR as develop branch is 5 commits behind.

### CODE REVIEW

**Comment by derlin** [comment]
Hello there!
You did well, develop is just a toy branch for me.
I approved the build, and will merge if all is green.

Thank you so much for the contribution and for taking the time to go over this repo, it feels good to know there is someone out there ;)

**Comment by derlin** [comment]
It seems the docker build fails on installing poetry. It is a mess on QEMU/ARM now that they upgraded their install script.
I will test on my side as well, keep me posted if you make it work !

PS: for the final rebase, can you please edit the commit message to follow conventional commit ?

**Comment by S0obi** [comment]
Hey, I will put back the installation of gcc and others, unfortunately I was hoping the OS upgrade to fix it (there was a bit of magical thinking here :)). It's not yet clear for me why it's not working on the Github Action agent.

**Comment by derlin** [comment]
thanks !

**Pull request merged**
